### ISSUE TITLE
PHP-FPM Crashes when Hugepages are Enabled

### ISSUE THREAD

**Issue by cdmastercom** [passbolt/charts-passbolt#47] opened 2023-08-25 02:36 UTC
When running in a microk8s cluster with Hugepages enable on the host VM, the PHP-FPM process inside the 'passbolt-depl-srv' pod continually crashes. This manifests as an unhealth pod:

```bash
> kubectl get pods -n passbolt
passbolt-depl-srv-59cb6bcdfb-6ptx8        0/1     Running     0 134m
```

Logs:
```bash
> kubectl logs -n passbolt passbolt-depl-srv-59cb6bcdfb-6ptx8
... (More above)
2023-08-25 02:24:25,508 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-25 02:24:25,508 WARN exited: php-fpm (terminated by SIGBUS (core dumped); not expected)
2023-08-25 02:24:26,512 INFO spawned: 'php-fpm' with pid 560
2023-08-25 02:24:27,643 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-25 02:24:27,644 WARN exited: php-fpm (terminated by SIGBUS (core dumped); not expected)
2023-08-25 02:24:28,648 INFO spawned: 'php-fpm' with pid 561
2023-08-25 02:24:28,795 WARN exited: php-fpm (terminated by SIGBUS (core dumped); not expected)
2023-08-25 02:24:29,801 INFO spawned: 'php-fpm' with pid 562
2023-08-25 02:24:30,943 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-25 02:24:30,946 WARN exited: php-fpm (terminated by SIGBUS (core dumped); not expected)
2023-08-25 02:24:31,949 INFO spawned: 'php-fpm' with pid 563
2023-08-25 02:24:33,090 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-25 02:24:33,090 WARN exited: php-fpm (terminated by SIGBUS (core dumped); not expected)
2023-08-25 02:24:34,093 INFO spawned: 'php-fpm' with pid 564
```

This behaviour can be worked around by disabling the PHP opcache in the pod.

```bash
> cat /etc/php/8.2/fpm/php.ini  | grep opcache
;zend_extension=opcache
[opcache]
opcache.enable=0
;opcache.enable_cli=0
;opcache.memory_consumption=128
;opcache.interned_strings_buffer=8
... (more below)
```

At which point PHP-FPM immediately works. For your reference, please see: https://github.com/kubernetes/kubernetes/issues/71233

In my case disabling hugepages is troublesome since we require it for Mayastor. There may be a better workaround compared to changing the PHP config, but it worked for me.

**Comment by dlen** [comment] 2023-08-25 06:08
Hi @cdmastercom !

Have you tried using this feature before? https://kubernetes.io/docs/tasks/manage-hugepages/scheduling-hugepages/

**Comment by dlen** [comment] 2023-09-27 11:36
Hello again!

Have you tried to enable opcache hugepages support? https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.huge_code_pages

**Comment by dlen** [comment] 2024-04-25 15:06
I'm closing this as I'm unable to reproduce and you seem to have a workaround disabling opcache

**Closed as completed by dlen** 2024-04-25 15:06 UTC
Labels: help wanted
